"""Redis-backed replay buffer for WS message recovery."""

from __future__ import annotations

import json
import logging
from typing import Any, Optional

from apps.server.src.storage.redis import RedisClient

logger = logging.getLogger(__name__)


class ReplayBuffer:
    """Redis Streams-backed replay buffer for message recovery.

    Uses Redis Streams for:
    - Ordered IDs (auto-generated by XADD)
    - Range queries (XRANGE)
    - Automatic trimming (XTRIM MAXLEN)
    """

    def __init__(self, redis: RedisClient, max_messages: int = 100):
        self.redis = redis
        self.max_messages = max_messages

    async def append(
        self,
        session_id: str,
        direction: str,
        message: dict[str, Any],
    ) -> str:
        """Append message to replay stream.

        Args:
            session_id: Session identifier
            direction: Message direction ("server" or "client" or "pending_client")
            message: Message to store

        Returns:
            Stream entry ID
        """
        stream_id = await self.redis.append_replay(
            session_id,
            message,
            direction,
        )
        logger.debug(
            f"Appended to replay buffer: session={session_id}, "
            f"direction={direction}, id={stream_id}"
        )
        return stream_id

    async def get_since(
        self,
        session_id: str,
        since_seq: int,
        direction: str = "server",
    ) -> list[dict[str, Any]]:
        """Get messages since given sequence number.

        Args:
            session_id: Session identifier
            since_seq: Last sequence number seen by peer
            direction: Message direction to retrieve

        Returns:
            List of messages to replay
        """
        # Get all messages from stream
        messages = await self.redis.get_replay_since(
            session_id,
            since_id="0",
            direction=direction,
        )

        # Filter by sequence number
        replay_messages = [
            msg for msg in messages
            if msg.get("seq", 0) > since_seq
        ]

        logger.debug(
            f"Replay buffer query: session={session_id}, "
            f"since_seq={since_seq}, found={len(replay_messages)}"
        )
        return replay_messages

    async def get_pending_client_messages(
        self,
        session_id: str,
    ) -> list[dict[str, Any]]:
        """Get messages that were pending for disconnected client.

        Args:
            session_id: Session identifier

        Returns:
            List of messages that were buffered while client was disconnected
        """
        return await self.redis.get_replay_since(
            session_id,
            since_id="0",
            direction="pending_client",
        )

    async def clear_pending_client(self, session_id: str) -> None:
        """Clear pending client messages after successful delivery."""
        # Use Redis client directly to delete stream
        await self.redis.client.delete(f"sess:{session_id}:replay:pending_client")

    async def trim(self, session_id: str, direction: str = "server") -> None:
        """Trim replay stream to max size."""
        await self.redis.trim_replay(session_id, direction)

    async def get_last_seq(self, session_id: str, direction: str = "server") -> int:
        """Get the last sequence number in the replay buffer."""
        messages = await self.redis.get_replay_since(
            session_id,
            since_id="0",
            direction=direction,
        )
        if messages:
            return max(msg.get("seq", 0) for msg in messages)
        return 0


class ReplayManager:
    """Manages replay buffers for multiple sessions."""

    def __init__(self, redis: RedisClient):
        self.redis = redis
        self._buffers: dict[str, ReplayBuffer] = {}

    def get_buffer(self, session_id: str) -> ReplayBuffer:
        """Get or create replay buffer for session."""
        if session_id not in self._buffers:
            self._buffers[session_id] = ReplayBuffer(self.redis)
        return self._buffers[session_id]

    async def store_outbound(
        self,
        session_id: str,
        message: dict[str, Any],
    ) -> None:
        """Store outbound (server → client) message for replay."""
        buffer = self.get_buffer(session_id)
        await buffer.append(session_id, "server", message)

    async def store_inbound(
        self,
        session_id: str,
        message: dict[str, Any],
    ) -> None:
        """Store inbound (client → server) message for replay."""
        buffer = self.get_buffer(session_id)
        await buffer.append(session_id, "client", message)

    async def get_replay_messages(
        self,
        session_id: str,
        last_server_seq_seen: int,
    ) -> list[dict[str, Any]]:
        """Get messages to replay on reconnect."""
        buffer = self.get_buffer(session_id)

        # Get server → client messages since last seen
        messages = await buffer.get_since(
            session_id,
            last_server_seq_seen,
            direction="server",
        )

        # Also get any pending messages
        pending = await buffer.get_pending_client_messages(session_id)
        messages.extend(pending)

        # Sort by sequence number
        messages.sort(key=lambda m: m.get("seq", 0))

        return messages

    async def handle_reconnect(
        self,
        session_id: str,
        last_server_seq_seen: int,
        last_client_seq_sent: int,
    ) -> tuple[list[dict[str, Any]], int]:
        """Handle client reconnection.

        Args:
            session_id: Session identifier
            last_server_seq_seen: Last server seq the client received
            last_client_seq_sent: Last client seq the client sent

        Returns:
            Tuple of (messages_to_replay, resume_from_seq)
        """
        # Get messages to replay
        messages = await self.get_replay_messages(session_id, last_server_seq_seen)

        # Calculate resume sequence
        buffer = self.get_buffer(session_id)
        last_seq = await buffer.get_last_seq(session_id, "server")
        resume_seq = last_seq + 1 if last_seq > 0 else 1

        # Clear pending messages after preparing replay
        await buffer.clear_pending_client(session_id)

        logger.info(
            f"Reconnect prepared: session={session_id}, "
            f"replay_count={len(messages)}, resume_seq={resume_seq}"
        )

        return messages, resume_seq

    def remove_buffer(self, session_id: str) -> None:
        """Remove replay buffer for ended session."""
        self._buffers.pop(session_id, None)
